--liquibase formatted sql

--changeset anshu:silver-customer-001

CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMER_ID VARCHAR NOT NULL,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    DATE_OF_BIRTH DATE,
    CITY VARCHAR,
    STATE VARCHAR,
    CUSTOMER_SEGMENT VARCHAR,
    CUSTOMER_STATUS VARCHAR,
    CREATED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ,
    INGESTED_AT TIMESTAMP_NTZ,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);