--liquibase formatted sql

--changeset anshu:silver-account-001

CREATE TABLE IF NOT EXISTS SILVER.ACCOUNT (
    ACCOUNT_ID VARCHAR NOT NULL,
    CUSTOMER_ID VARCHAR NOT NULL,
    ACCOUNT_TYPE VARCHAR,
    ACCOUNT_STATUS VARCHAR,
    OPENING_DATE DATE,
    BALANCE NUMBER(18,2),
    CURRENCY VARCHAR,
    UPDATED_AT TIMESTAMP_NTZ,
    INGESTED_AT TIMESTAMP_NTZ,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

--rollback DROP TABLE IF EXISTS SILVER.ACCOUNT;
