--liquibase formatted sql

--changeset anshu:silver-transaction-001

CREATE TABLE IF NOT EXISTS SILVER.TRANSACTION (
    TRANSACTION_ID VARCHAR NOT NULL,
    ACCOUNT_ID VARCHAR NOT NULL,
    CUSTOMER_ID VARCHAR NOT NULL,
    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ,
    TRANSACTION_TYPE VARCHAR,
    AMOUNT NUMBER(18,2),
    CURRENCY VARCHAR,
    MERCHANT VARCHAR,
    TRANSACTION_STATUS VARCHAR,
    INGESTED_AT TIMESTAMP_NTZ,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

--rollback DROP TABLE IF EXISTS SILVER.TRANSACTION;