--liquibase formatted sql

--changeset anshu:silver-support-ticket-001

CREATE TABLE IF NOT EXISTS SILVER.SUPPORT_TICKET (
    TICKET_ID VARCHAR NOT NULL,
    CUSTOMER_ID VARCHAR NOT NULL,
    CREATED_AT TIMESTAMP_NTZ,
    CATEGORY VARCHAR,
    PRIORITY VARCHAR,
    STATUS VARCHAR,
    SUBJECT VARCHAR,
    DESCRIPTION VARCHAR,
    INGESTED_AT TIMESTAMP_NTZ,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

--rollback DROP TABLE IF EXISTS SILVER.SUPPORT_TICKET;
