--liquibase formatted sql

--changeset anshu:silver-product-001

CREATE TABLE IF NOT EXISTS SILVER.PRODUCT (
    PRODUCT_ID VARCHAR NOT NULL,
    PRODUCT_NAME VARCHAR,
    PRODUCT_TYPE VARCHAR,
    PRODUCT_CATEGORY VARCHAR,
    ANNUAL_FEE NUMBER(18,2),
    INTEREST_RATE NUMBER(10,4),
    STATUS VARCHAR,
    INGESTED_AT TIMESTAMP_NTZ,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

--rollback DROP TABLE IF EXISTS SILVER.PRODUCT;