liquibase.command.url=jdbc:snowflake://${env.SNOWFLAKE_ACCOUNT}.snowflakecomputing.com/?db=${env.SNOWFLAKE_DATABASE}&schema=${env.SNOWFLAKE_SCHEMA}&warehouse=${env.SNOWFLAKE_WAREHOUSE}&role=${env.SNOWFLAKE_ROLE}

liquibase.command.username=${env.SNOWFLAKE_USER}

liquibase.command.password=${env.SNOWFLAKE_PASSWORD}

liquibase.command.defaultSchemaName=BRONZE

liquibase.command.changelogFile=changelog-master.yml