liquibase.command.url=jdbc:snowflake://${SNOWFLAKE_ACCOUNT}.snowflakecomputing.com/?db=${SNOWFLAKE_DATABASE}&schema=${SNOWFLAKE_SCHEMA}&warehouse=${SNOWFLAKE_WAREHOUSE}&role=${SNOWFLAKE_ROLE}&authenticator=${SNOWFLAKE_AUTHENTICATOR}

liquibase.command.username=${SNOWFLAKE_USER}

liquibase.command.defaultSchemaName=${SNOWFLAKE_SCHEMA}

liquibase.command.changelogFile=changelog-master.yml