--USE DATABASE FINAI_DEV;
--USE SCHEMA BRONZE;

--liquibase formatted sql

--changeset anshu:bronze-customer-raw-001

CREATE OR REPLACE TABLE CUSTOMER_RAW (
    CUSTOMER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    DATE_OF_BIRTH DATE,
    CITY VARCHAR,
    STATE VARCHAR,
    CUSTOMER_SEGMENT VARCHAR,
    CUSTOMER_STATUS VARCHAR,
    CREATED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);