--liquibase formatted sql

--changeset anshu:bronze-account-raw-001

CREATE TABLE IF NOT EXISTS ACCOUNT_RAW (
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    ACCOUNT_TYPE VARCHAR,
    ACCOUNT_STATUS VARCHAR,
    OPENING_DATE DATE,
    BALANCE NUMBER(18,2),
    CURRENCY VARCHAR,
    UPDATED_AT TIMESTAMP_NTZ,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

--rollback DROP TABLE IF EXISTS ACCOUNT_RAW;
