--liquibase formatted sql

--changeset anshu:bronze-transaction-raw-001

CREATE TABLE IF NOT EXISTS TRANSACTION_RAW (
    TRANSACTION_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ,
    TRANSACTION_TYPE VARCHAR,
    AMOUNT NUMBER(18,2),
    CURRENCY VARCHAR,
    MERCHANT VARCHAR,
    TRANSACTION_STATUS VARCHAR,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);