--liquibase formatted sql

--changeset anshu:bronze-support-ticket-raw-001

CREATE TABLE IF NOT EXISTS SUPPORT_TICKET_RAW (
    TICKET_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    CREATED_AT TIMESTAMP_NTZ,
    CATEGORY VARCHAR,
    PRIORITY VARCHAR,
    STATUS VARCHAR,
    SUBJECT VARCHAR,
    DESCRIPTION VARCHAR,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

--rollback DROP TABLE IF EXISTS SUPPORT_TICKET_RAW;
