CREATE OR REPLACE TABLE SUPPORT_TICKET_RAW (
    TICKET_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    CREATED_AT TIMESTAMP_NTZ,
    CATEGORY VARCHAR,
    PRIORITY VARCHAR,
    STATUS VARCHAR,
    SUBJECT VARCHAR,
    DESCRIPTION VARCHAR,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);