--liquibase formatted sql

--changeset anshu:bronze-product-raw-001

CREATE TABLE IF NOT EXISTS PRODUCT_RAW (
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    PRODUCT_TYPE VARCHAR,
    PRODUCT_CATEGORY VARCHAR,
    ANNUAL_FEE NUMBER(18,2),
    INTEREST_RATE NUMBER(10,4),
    STATUS VARCHAR,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

--rollback DROP TABLE IF EXISTS PRODUCT_RAW;