--liquibase formatted sql

--changeset anshu:bronze-ingestion-file-log-001

CREATE TABLE IF NOT EXISTS INGESTION_FILE_LOG (
    SOURCE_NAME VARCHAR NOT NULL,
    FILE_NAME VARCHAR NOT NULL,
    FILE_SIZE NUMBER,
    FILE_HASH VARCHAR,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ROWS_LOADED NUMBER,
    LOAD_STATUS VARCHAR,
    PRIMARY KEY (SOURCE_NAME, FILE_NAME)
);